# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  director: 'logs'
  link-name: 'latest_log'
  show-line: true
  # LowercaseLevelEncoder:小写, LowercaseColorLevelEncoder:小写带颜色,CapitalLevelEncoder: 大写, CapitalColorLevelEncoder: 大写带颜色,
  encode-level: 'CapitalLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

# mysql configuration
mysql:
  path: '172.17.0.1:3306'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  db-name: 'luban'
  username: 'root'
  password: '123456'
  max-idle-conns: 10
  max-open-conns: 100
  conn-max-idle-time: 60
  conn-max-life-time: 600
  log-mode: false
  log-zap: ""

# casbin configuration
casbin:
  model-path: './etc/rbac_model.conf'

# system configuration
system:
  env: 'private'  # Change to "develop" to skip authentication for development mode,  change to "private" authentication
  addr: 8999
  rpc: 40737
  db-type: 'mysql'


redis:
  addr: '127.0.0.1:6379'
  db: 0
  username: ''
  password: ''

# cloudSync Task
crontab:
  aliyun: "00 */2 * * *"

# dingding qrcode
dingtalk:
  appid: ''
  secret: ''
  url: 'https://oapi.dingtalk.com'
  # 允许登录的邮箱后缀 test@luban.com [luban.com]
  allow-suffix: 'luban.com'
